<?xml version="1.0"?>
<doc>
    <assembly>
        <name>Libx.Fix.AutoCameraTarget</name>
    </assembly>
    <members>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionStatus.None">
            <summary>
            There is nothing visible in the viewport.
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionStatus.Outside">
            <summary>
            The line is outside any visible element and its bounding boxes.
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionStatus.OnMesh">
            <summary>
            There is an intersection with a mesh.
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionStatus.OnBBox">
            <summary>
            There is an intersection with a bounding box.
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionStatus.OnVisibleBBox">
            <summary>
            There is an intersection with the bounding box of all visible elements.
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionData.Status">
            <summary>
            Type of intersection found.
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionData.Rayline">
            <summary>
            The line under the mouse pointer to the far plane Frustum
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionData.FrustumFrontPlane">
            <summary>
            Plan in front of the camera at the center of VisibleBBox.
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionData.ObjectCount">
            <summary>
            Number of objects under the mouse.
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionData.ActiveBBox">
            <summary>
            The bounding box of the element closest to the camera.
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionData.VisibleBBox">
            <summary>
            Box containing the objects visible in the viewport.
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.IntersectionData.TargetPoint">
            <summary>
            The target point of the camera
            </summary>
        </member>
        <member name="M:Libx.Fix.AutoCameraTarget.Intersector._RayBoxIntersectionCenter(System.Double[],System.Double[],Rhino.Geometry.BoundingBox)">
            <summary>
            same as _RayBoxIntersection but returns the midpoint of the ray line trimmed by the bounding box
            </summary>
        </member>
        <member name="M:Libx.Fix.AutoCameraTarget.Intersector._RayBoxIntersection(System.Double[],System.Double[],Rhino.Geometry.BoundingBox)">
            <summary>
            Ray-AABB (Axis Aligned Bounding Box) intersection.
            <br/> <see href="https://tavianator.com/2011/ray_box.html"/>
            <br/> <see href="https://tavianator.com/2015/ray_box_nan.html"/>
            </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.Cursor._initiaCursorPos">
            <summary>
            Viewport point when the mouse button is down.
            </summary>
        </member>
        <member name="T:Libx.Fix.AutoCameraTarget.RMBListener">
            <summary>
                Wrapper class above <see cref="T:Libx.Fix.AutoCameraTarget.NavigationListener"/> </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.NavigationListener._started">
            <summary>
                Flag to cancel or not the MouseUp event.</summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.NavigationListener._lock">
            <summary>
                Flag blocking `OnMouseMove` event after `EF.Mouse.Position=...`</summary>
        </member>
        <member name="M:Libx.Fix.AutoCameraTarget.NavigationListener.SetModifierCallback(Libx.Fix.AutoCameraTarget.ModifierKey,System.Action{Eto.Drawing.Point},System.Object)">
            <summary>
                Define a callback function when moving the mouse.</summary>
            <param name="modifier">
                One of the keys from <see cref="T:Libx.Fix.AutoCameraTarget.ModifierKey"/>
                or <see cref="F:Libx.Fix.AutoCameraTarget.ModifierKey.None"/> if no modifier is required for this action.</param>
            <param name="action">
                The action to execute.</param>
            <param name="tag">
                Value sent to `OnActionChange` when modifier key and action change.</param>
        </member>
        <member name="M:Libx.Fix.AutoCameraTarget.NavigationListener.OnActionChange(System.Object,System.Object)">
            <summary>
                Function called when the modifier key and its associated action change.
                see <seealso cref="M:Libx.Fix.AutoCameraTarget.NavigationListener.SetModifierCallback(Libx.Fix.AutoCameraTarget.ModifierKey,System.Action{Eto.Drawing.Point},System.Object)"/> </summary>
            <param name="previousTag">
                Previously active action tag</param>
            <param name="currentTag">
                New active action tag</param>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.Camera.PanX">
            <summary> Offset along camera X axis. </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.Camera.PanY">
            <summary> Offset along camera Y (Up) axis </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.Camera.PanZ">
            <summary> Offset along camera Z (Direction) axis </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.Camera.RotX">
            <summary> Rotation of the camera around the X axis.
            This rotation is performed before the Z rotation. </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.Camera.RotZ">
            <summary> Rotation of the camera around the Z axis.
            This rotation is performed before the X rotation. </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.Camera.PosX">
            <summary> Global X position of all transformations </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.Camera.PosY">
            <summary> Global Y position of all transformations </summary>
        </member>
        <member name="F:Libx.Fix.AutoCameraTarget.Camera.PosZ">
            <summary> Global Z position of all transformations </summary>
        </member>
    </members>
</doc>
